[package]
name = "tower-stratum"
authors = ["plebhash <plebhash@proton.me>"]
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

# tokio
tokio = { version = "1.44.1", features = ["full", "tracing"] }
tokio-util = "0.7.15"

# tower
tower = { version = "0.5.0", features = ["full"] }

# misc
async-channel = "1.5.1"
serde = { version = "1.0.89", features = ["derive", "alloc"]}
tracing = "0.1"
tracing-subscriber = "0.3.19"
secp256k1 = { version = "0.28.2", default-features = false }
dashmap = "6.1.0"

# SRI
stratum-common = { git = "https://github.com/stratum-mining/stratum", branch = "v1.4.0", features = ["with_network_helpers"]}
key-utils = { git = "https://github.com/stratum-mining/stratum", branch = "v1.4.0" }

[dev-dependencies]
once_cell = "1.19.0"
integration_tests_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "v1.4.0" }
hex = "0.4.3"

# tokio debugging
console-subscriber = { version = "0.4.1" }

