server_addr = "127.0.0.1:3333"
auth_pk = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
n_extended_channels = 0
n_standard_channels = 2
user_identity = "tower-stratum"
device_id = "mining-client-cpu-miner"